### ISSUE TITLE
Check for 0.0001 EOS is incorrect

### ISSUE THREAD

**Issue by michaeljyeates** [EOSVR/EOSVR#2]
The check in the code for a minimum donation is incorrect.

https://github.com/EOSVR/EOSVR/blob/master/airdrop/airdrop.cpp#L50

This line should read > 0 instead of > 1, at the moment the minimum is 0.0002

**Comment by wsdfz** [comment]
This part logic is to calculate the total number of donation EOS.
Do not calcuate the airdrop users, and only calculate in case "> 1" to save CPU of users.
